/* Creates the committed, fixed image bank. Run with node scripts/generate-data.cjs. */
const fs = require('node:fs');
const path = require('node:path');
const { rng } = require('../src/core.js');
const root = path.resolve(__dirname, '..');
const random = rng(20260923), samples = [];
fs.mkdirSync(path.join(root, 'nuclei'), { recursive: true });
fs.mkdirSync(path.join(root, 'data'), { recursive: true });
function inside(x, y, points) {
  let hit = false;
  for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
    const a = points[i], b = points[j];
    if ((a[1] > y) !== (b[1] > y) && x < (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]) + a[0]) hit = !hit;
  }
  return hit;
}
for (let pair = 0; pair < 50; pair++) {
  // Nuisance variables are paired across labels; no brightness/size label cue is deliberately introduced.
  const radius = 4.15 + random() * 1.0, aspect = 0.83 + random() * 0.34;
  const cx = 8 + (random() - 0.5) * 0.9, cy = 8 + (random() - 0.5) * 0.9;
  const stain = 0.70 + random() * 0.28, rot = random() * Math.PI * 2;
  for (let label = 0; label <= 1; label++) {
    const amp = label ? 0.13 + random() * 0.13 : 0.009 + random() * 0.015;
    const freq = 3 + Math.floor(random() * 4), phase = random() * Math.PI * 2;
    const fine = label ? 0.035 + random() * 0.045 : 0.004;
    const points = Array.from({ length: 192 }, (_, k) => {
      const t = k / 192 * Math.PI * 2;
      const r = radius * (1 + amp * Math.cos(freq * t + phase) + fine * Math.sin(7 * t + phase * 1.7));
      const u = r * Math.cos(t) * aspect, v = r * Math.sin(t) / aspect;
      return [cx + u * Math.cos(rot) - v * Math.sin(rot), cy + u * Math.sin(rot) + v * Math.cos(rot)];
    });
    const pixels = Array.from({ length: 256 }, (_, i) => {
      let coverage = 0;
      for (let sy = 0; sy < 4; sy++) for (let sx = 0; sx < 4; sx++) if (inside(i % 16 + (sx + 0.5) / 4, Math.floor(i / 16) + (sy + 0.5) / 4, points)) coverage++;
      return +((coverage / 16) * stain).toFixed(4);
    });
    const id = `N${String(pair * 2 + label + 1).padStart(3, '0')}`, split = pair < 40 ? 'train' : 'test';
    const contour = points.map(p => p.map(v => +v.toFixed(3)));
    const color = [247, 241, 250].map((v, i) => Math.round(v + stain * ([95, 53, 146][i] - v)));
    const d = 'M' + contour.map(p => p.join(',')).join('L') + 'Z';
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" role="img" aria-label="Synthetic ${label ? 'irregular' : 'regular'} nucleus ${id}"><rect width="16" height="16" fill="#f7f1fa"/><path d="${d}" fill="rgb(${color.join(',')})"/></svg>\n`;
    fs.writeFileSync(path.join(root, 'nuclei', `${id}.svg`), svg);
    samples.push({ id, pair: pair + 1, split, label, pixels, contour, stain: +stain.toFixed(4) });
  }
}
const dataset = { version: 1, seed: 20260923, side: 16, labels: ['Regular', 'Irregular'], samples };
fs.writeFileSync(path.join(root, 'data', 'nuclei.js'), `/* Fixed synthetic teaching dataset; generated by scripts/generate-data.cjs. */\nglobalThis.NUCLEI_DATA = ${JSON.stringify(dataset)};\n`);
fs.writeFileSync(path.join(root, 'data', 'manifest.csv'), 'id,split,label,pair,image\n' + samples.map(s => `${s.id},${s.split},${s.label ? 'irregular' : 'regular'},${s.pair},nuclei/${s.id}.svg`).join('\n') + '\n');
console.log(`Created ${samples.length} nuclei: 80 training (40/40), 20 test (10/10).`);
